[versions]
# libraries
jackson = "2.18.2"
junit = "4.13.2"

# plugins
sonarqube = "6.0.1.5171"
intelliJPlatform = "2.2.1"

[libraries]
jakson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
sonarqube = {id = "org.sonarqube", version.ref = "sonarqube"}