name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: jetbrains
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar


    - name: Build with Gradle
      run: ./gradlew build --info
      env:
        CI: true

    - name: Scan project using SonarQube
      run: ./gradlew sonar --info
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Verify Plugin on IntelliJ Platforms
      run: ./gradlew verifyPlugin --info

    - name: Stop Gradle daemon
      run: ./gradlew --stop
