name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar


    - name: Build with Gradle
      run: ./gradlew build --info

    - name: Scan project using SonarQube
      run: ./gradlew sonarqube --info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Verify Plugin on IntelliJ Platforms
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
      with:
        ide-versions: |
          ideaIC:2018.2
          ideaIC:2019.2
          ideaIC:2020.2

    - name: Get log file path and print contents
      run: |
        echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}

    - name: Stop Gradle daemon
      run: ./gradlew --stop
